workflows:
  ios_release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.tasdemir.habitfree"

    triggers:
      tag: true

    scripts:
      - name: Flutter clean & pub get
        script: |
          cd bagimliss
          flutter --version
          flutter clean
          flutter pub get

      - name: Verify bundle id
        script: |
          cd bagimliss
          grep -n "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || true

      - name: CocoaPods
        script: |
          cd bagimliss/ios
          pod install --repo-update

      - name: Build iOS (release IPA)
        script: |
          cd bagimliss
          BUILD_NAME=${CM_TAG:-1.0.0}
          flutter build ipa --release \
            --build-name="$BUILD_NAME" --build-number="$CM_BUILD_ID"

    publishing:
      app_store_connect:
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
