workflows:
  # ------------------------------
  # ANDROID: Yalnızca AAB üretir.
  # ------------------------------
  android_release:
    name: Android Release (AAB)
    max_build_duration: 60
    instance_type: mac_mini_m
    environment:
      flutter: stable
      android: latest
      vars:
        ANDROID_API_LEVEL: "34"          # Gerektiğinde 35 yap
        ANDROID_BUILD_TOOLS: "34.0.0"    # Gerektiğinde 35.0.0
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - /usr/local/share/android-sdk
    scripts:
      - name: Accept Android SDK licenses
        script: |
          yes | sdkmanager --licenses

      - name: Pre-install Android SDK components (with retries)
        script: |
          set -e
          TO_INSTALL=("platform-tools" "platforms;android-${ANDROID_API_LEVEL}" "build-tools;${ANDROID_BUILD_TOOLS}")
          for i in {1..3}; do
            echo "Attempt $i to install SDK components..."
            sdkmanager "${TO_INSTALL[@]}" && break || sleep 15
            if [ "$i" -eq 3 ]; then
              echo "Retrying once with --no_https ..."
              sdkmanager --no_https "${TO_INSTALL[@]}"
            fi
          done

      - name: Increase Gradle HTTP timeouts (optional)
        script: |
          echo "org.gradle.internal.
