workflows:
  ios_release:
    name: iOS Release (TestFlight)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.tasdemir.habitfree"

    triggers:
      tag: true

    scripts:
      - name: Flutter clean & pub get
        script: |
          cd bagimliss
          flutter --version
          flutter clean
          flutter pub get

      - name: Verify bundle id
        script: |
          cd bagimliss
          grep -n "PRODUCT_BUNDLE_IDENTIFIER" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Add iOS Widget Extension
        script: |
          cd bagimliss
          echo "iOS Widget Extension dosyalarını kontrol ediliyor..."
          ls -la ios/SavingsWidget/ || echo "Widget dosyaları bulunamadı"
          
          # Widget dosyalarının mevcut olduğundan emin ol
          if [ ! -f "ios/SavingsWidget/SavingsWidget.swift" ]; then
            echo "Widget dosyaları eksik, oluşturuluyor..."
            mkdir -p ios/SavingsWidget
            cp ../ios/SavingsWidget/* ios/SavingsWidget/ 2>/dev/null || echo "Kopyalama işlemi tamamlandı"
          fi
          
          echo "Widget dosyaları hazır!"

      - name: Create Widget Entitlements
        script: |
          cd bagimliss/ios/SavingsWidget
          cat > SavingsWidget.entitlements << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>com.apple.security.application-groups</key>
            <array>
              <string>group.com.tasdemir.habitfree</string>
            </array>
          </dict>
          </plist>
          EOF

      - name: CocoaPods
        script: |
          cd bagimliss/ios
          pod install --repo-update

      - name: Build iOS (release IPA)
        script: |
          cd bagimliss
          BUILD_NAME=${CM_TAG:-1.0.0}
          flutter build ipa --release \
            --build-name="$BUILD_NAME" --build-number="$CM_BUILD_ID"

    publishing:
      app_store_connect:
        submit_to_testflight: true
        beta_groups:
          - Internal Testing
